spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        type:
          wrapper_array_handling: ALLOW
    database: postgresql

jwt:
  key: ffEhtpE5/lfABdWIg7q6brJodYfmo/oig+3GLc/SN68xsEzsAnbqsIwEjjd3NYNxiycTTNsNUOWHSZQy1pLz7MzROT+VQ1ZOnQLHj2T79DcJV5rxr0LvbzgYWqEjz9PmiZkppWbaf0yGa3ZZFNHEsoc/5ni4Ii6liXyr2wEE8jo=
  expirationAccessToken: 60000
  expirationRefreshToken: 600000

server:
  port: 8081